spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/dbchangelog.xml
    enabled: true